DELETE http://localhost:3001/api/persons/2

### 
GET https://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "ggg",
    "number": "1234567899"
}

###
DELETE http://localhost:3001/api/persons/67736c3f29d2dee9ba6175ef
###
GET https://localhost:3001/api/persons